### ISSUE TITLE
understand shell vars in volumes

### ISSUE THREAD

**Issue by komuw** [komuw/meli#104]
the following compose file fails
```
myTing:
     image: 'redis:3.0-alpine'
    volumes:
      - $HOME/.someFile:/root/.someFile
```
