### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by komuw** [komuw/meli#96]
Thank you for using meli and taking your time to report an issue to us.                    

## What operating system and version of operating system are you using?
osx
## What version of meli are you using? run meli `meli --version`
latest
## What did you do? (be as detailed as you can)
`meli -up`
## What did you expect to see/happen/not happen?
- running services
## What happened instead? 
- panic 
## Paste the log output generated by `meli -up`. Please remember to remove any sensitive items from the log before copy-pasting.                                           
```
panic: runtime error: index out of range

goroutine 14 [running]:
github.com/komuw/meli/api.CreateContainer(0x1375a20, 0xc4200180d0, 0x13776c0, 0xc42011bd80, 0xc4200cf760, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/komuw/meli/api/container.go:57 +0x15b7
main.startComposeServices(0x1375a20, 0xc4200180d0, 0xc42011bd80, 0xc42025f530, 0xc4200cf760)
	/root/go/src/github.com/komuw/meli/main.go:118 +0xb0
created by main.main
	/root/go/src/github.com/komuw/meli/main.go:93 +0x586
```

## If you don't mind, copy-paste the docker-compose.yml file that you were using(or an equivalent compose file that reproduces the same issue)?
```
version: '3'
services:
  redis:
    image: 'redis:3.0-alpine'
    environment:
      - RACK_ENV=development
      - type=database
    ports:
      - 6379
```
